'use strict';
const {app,BrowserWindow,clipboard}=require('electron');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const root=path.join(__dirname,'..');
process.env.MOJI_DATA=fs.mkdtempSync(path.join(os.tmpdir(),'moji-smoke-'));
process.argv.push('--background');
const moji=require('../main.cjs');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const timeout=setTimeout(()=>{console.error('SMOKE TIMEOUT');app.exit(2)},90000);
async function until(fn,label){for(let i=0;i<100;i++){if(await fn())return;await sleep(50)}throw new Error('Timeout: '+label)}
app.whenReady().then(async()=>{
 await until(()=>moji.getWindow()?.webContents&&!moji.getWindow().webContents.isLoading(),'window');
 const win=moji.getWindow(),js=code=>win.webContents.executeJavaScript(code).catch(e=>{throw new Error(code+'\n'+e.message)}),errors=[];
 win.webContents.on('console-message',e=>{if(e.level>=3)errors.push(e.message)});
 await until(()=>js('document.documentElement?.dataset.ready'), 'renderer ready');
 console.log('Renderer listo');
 const hintTop=()=>js('document.getElementById("preview-hint").getBoundingClientRect().top');
 const idleTop=await hintTop();assert.equal(await js('document.getElementById("preview-label").textContent'),'');
 await js('document.querySelector(".character").dispatchEvent(new Event("mouseenter"))');
 assert.notEqual(await js('document.getElementById("preview-label").textContent'),'');assert.equal(await hintTop(),idleTop,'preview hint keeps its place when a label appears');
 assert.equal(await js('document.querySelectorAll(".tab").length'),4);
 assert.equal(await js('document.querySelectorAll(".character").length'),24);
 const out=path.join(root,'.shots');fs.mkdirSync(out,{recursive:true});
 const trayIcon=moji.icon();assert.deepEqual(trayIcon.getSize(),{width:16,height:16});assert.deepEqual([...trayIcon.getScaleFactors()].sort((a,b)=>a-b),[1,1.25,1.5,2]);
 // The first capture right after showing can come back empty until a frame is committed.
 await moji.show(false);await sleep(300);await win.webContents.capturePage();await sleep(300);
 fs.writeFileSync(path.join(out,'frequent.png'),(await win.webContents.capturePage()).toPNG());
 await js('document.getElementById("tab-emoji").click()');
 await until(()=>js('document.querySelectorAll(".character").length').then(n=>n>1800),'emoji grid');
 await js('document.getElementById("search").value="pulgar arriba";document.getElementById("search").dispatchEvent(new Event("input"))');
 assert(await js(`!!document.querySelector('[data-id="1F44D"]')`));
 console.log('Búsqueda OK');
 await js('document.getElementById("tone").click()');await sleep(250);
 const rect=await js('(()=>{const r=document.querySelector(".ox-menu").getBoundingClientRect();return {x:r.x,y:r.y,b:r.bottom}})()');assert(rect.x>=0&&rect.y>=0&&rect.b<=536);
 await js('document.querySelectorAll(".ox-menuitem")[1].click()');await sleep(250);
 assert.equal(await js(`document.querySelector('[data-id="1F44D"] .glyph').textContent`),'👍🏻');
 // Real Win32 foreground and input, to a separate desktop window.
 const target=new BrowserWindow({width:500,height:230,show:false,backgroundColor:'#141414',webPreferences:{contextIsolation:true,nodeIntegration:false}});
 await target.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent('<title>Moji · prueba de inserción</title><body style="background:#141414;color:#eee;font-family:Segoe UI;padding:18px"><p>Prueba local de inserción de Moji</p><textarea id="input" autofocus style="width:95%;height:80px;font-size:25px"></textarea></body>'));
 target.show();target.focus();await sleep(250);await target.webContents.executeJavaScript('document.getElementById("input").focus()');
 const native=require('../src/native.cjs');
 const targetHwnd=target.getNativeWindowHandle().readBigUInt64LE();
 await until(async()=>{target.show();target.focus();native.focus(targetHwnd);await sleep(30);return BigInt(native.foreground())===targetHwnd},'test target focus');
 const clip=clipboard.readText();
 // Fire the registered chord via SendInput, rather than calling the toggle callback.
 const koffi=require('koffi'),u=koffi.load('user32.dll'),send=u.func('uint32_t __stdcall SendInput(uint32_t count, const void *events, int size)');
 const keys=[[0x11,0],[0x12,0],[0xBE,0],[0xBE,2],[0x12,2],[0x11,2]],buf=Buffer.alloc(keys.length*40);
 keys.forEach(([key,flag],i)=>{buf.writeUInt32LE(1,i*40);buf.writeUInt16LE(key,i*40+8);buf.writeUInt32LE(flag,i*40+12)});
 assert.equal(send(keys.length,buf,40),keys.length);
 await until(()=>win.isFocused(),'global shortcut');
 assert.equal(BigInt(moji.getTarget()),target.getNativeWindowHandle().readBigUInt64LE());
 await js(`document.getElementById('search').value='pulgar arriba';document.getElementById('search').dispatchEvent(new Event('input'));document.querySelector('[data-id="1F44D"]').click()`);
 await until(async()=>await target.webContents.executeJavaScript('document.getElementById("input").value')==='👍🏻','native emoji inserted');
 assert.equal(clipboard.readText(),clip,'insertion leaves clipboard unchanged');
 await until(()=>moji.getState().usage.some(i=>i.id==='1F44D'),'usage saved');
 assert.equal(moji.getState().usage.find(i=>i.id==='1F44D').count,1);
 await until(()=>win.isVisible()&&win.isFocused(),'panel stays open and focused after insert');
 await js('document.getElementById("tab-kaomoji").click()');await sleep(150);
 assert(await js('document.querySelectorAll(".character").length')>=60);
 fs.writeFileSync(path.join(out,'kaomoji.png'),(await win.webContents.capturePage()).toPNG());
 const kao=await js('document.querySelector(".character .glyph").textContent');
 await js('document.querySelector(".character").click()');
 await until(async()=>await target.webContents.executeJavaScript('document.getElementById("input").value')==='👍🏻'+kao,'kaomoji inserted');
 await until(()=>win.isVisible()&&win.isFocused(),'panel stays open and focused after insert');await js('document.getElementById("tab-symbol").click()');await sleep(120);
 fs.writeFileSync(path.join(out,'symbols.png'),(await win.webContents.capturePage()).toPNG());
 await js('document.getElementById("search").value="raiz";document.getElementById("search").dispatchEvent(new Event("input"));document.querySelector(".character").click()');
 await until(async()=>await target.webContents.executeJavaScript('document.getElementById("input").value')==='👍🏻'+kao+'√','symbol inserted');
 await until(()=>win.isVisible()&&win.isFocused(),'panel stays open and focused after insert');
 // Después de insertar, Esc cierra directo aunque haya una búsqueda escrita.
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await until(()=>!win.isVisible(),'Esc closes after insert');
 await moji.show();await sleep(250);await js('document.getElementById("settings").click()');await sleep(200);
 fs.writeFileSync(path.join(out,'settings.png'),(await win.webContents.capturePage()).toPNG());
 assert.equal(await js('document.getElementById("preferences").hidden'),false);
 await js('document.getElementById("back").click()');
 await js('document.getElementById("tab-frequent").click()');await sleep(150);
 assert.equal(await js('document.querySelectorAll(".character").length'),3);
 const disk=JSON.parse(fs.readFileSync(path.join(process.env.MOJI_DATA,'panel.json'),'utf8'));
 assert.equal(disk.usage['1F44D'].tone,1);
 await js('document.getElementById("settings").click();document.getElementById("reset-usage").click()');await sleep(350);
 const modal=await js('(()=>{const r=document.querySelector(".ox-modal").getBoundingClientRect();return {x:r.x,y:r.y,b:r.bottom,r:r.right}})()');
 assert(modal.x>=0&&modal.y>=0&&modal.b<=536&&modal.r<=416,'confirmation fits panel');
 await js('document.querySelector(".ox-modal__foot .ox-btn--primary").click()');await sleep(300);
 assert.equal(moji.getState().usage.length,0);
 await js('document.getElementById("back").click()');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await sleep(150);assert(!win.isVisible());
 assert.deepEqual(errors,[]);
 console.log('SMOKE OK: renderer + búsqueda + tonos + menú + atajo Win32 + inserción emoji/kaomoji/símbolo + portapapeles intacto + frecuencia en disco.');
 console.log('Capturas: '+out);
 target.destroy();clearTimeout(timeout);app.quit();
}).catch(err=>{console.error(err);clearTimeout(timeout);app.exit(1)});
